use chrono::Utc;
use serde_json::{Map, Value};
use thiserror::Error;
use uuid::Uuid;

use crate::{
    domain::{
        AppendRunEventRequest, CreateRunRequest, Run, RunDetails, RunEvent, RunEventType, RunStatus,
    },
    repository::{Repository, RepositoryError},
};

#[derive(Debug, Error)]
pub enum ServiceError {
    #[error("run ID must be a UUID")]
    InvalidRunId,
    #[error("{0}")]
    InvalidRequest(String),
    #[error("run not found")]
    RunNotFound,
    #[error("{0}")]
    Conflict(String),
    #[error(transparent)]
    Repository(#[from] RepositoryError),
}

#[derive(Clone)]
pub struct TrustCoreService {
    repository: Repository,
}

impl TrustCoreService {
    pub const fn new(repository: Repository) -> Self {
        Self { repository }
    }

    pub async fn create_run(&self, request: CreateRunRequest) -> Result<Run, ServiceError> {
        validate_create_run(&request)?;

        let now = Utc::now();
        let run = Run {
            run_id: Uuid::new_v4(),
            goal: request.goal.trim().to_owned(),
            tool: request.tool,
            status: RunStatus::Pending,
            current_node: None,
            created_at: now,
            updated_at: now,
        };
        let created_event = RunEvent {
            event_id: Uuid::new_v4(),
            run_id: run.run_id,
            sequence: 0,
            node_id: "run".to_owned(),
            event_type: RunEventType::RunCreated,
            payload: Map::from_iter([(
                "status".to_owned(),
                Value::String(RunStatus::Pending.as_str().to_owned()),
            )]),
            created_at: now,
        };

        self.repository
            .create_run(&run, &created_event)
            .await
            .map_err(Into::into)
    }

    pub async fn list_runs(&self) -> Result<Vec<Run>, ServiceError> {
        self.repository.list_runs().await.map_err(Into::into)
    }

    pub async fn get_run_details(&self, run_id: &str) -> Result<RunDetails, ServiceError> {
        let run_id = parse_run_id(run_id)?;
        let run = self
            .repository
            .get_run(run_id)
            .await?
            .ok_or(ServiceError::RunNotFound)?;
        let events = self.repository.list_events(run_id).await?;

        Ok(RunDetails { run, events })
    }

    pub async fn append_event(
        &self,
        run_id: &str,
        request: AppendRunEventRequest,
    ) -> Result<RunEvent, ServiceError> {
        let run_id = parse_run_id(run_id)?;
        validate_append_event(&request)?;

        let run = self
            .repository
            .get_run(run_id)
            .await?
            .ok_or(ServiceError::RunNotFound)?;
        let projection = event_projection(&run, &request)?;

        let event = RunEvent {
            event_id: Uuid::new_v4(),
            run_id,
            sequence: 0,
            node_id: request.node_id.trim().to_owned(),
            event_type: request.event_type,
            payload: request.payload,
            created_at: Utc::now(),
        };

        self.repository
            .append_event(
                &event,
                run.status,
                projection.status,
                projection.current_node.as_deref(),
            )
            .await
            .map_err(|error| match error {
                RepositoryError::RunStateChanged => ServiceError::Conflict(
                    "run state changed while appending the event; reload and retry".to_owned(),
                ),
                other => ServiceError::Repository(other),
            })
    }
}

struct EventProjection {
    status: Option<RunStatus>,
    current_node: Option<String>,
}

fn event_projection(
    run: &Run,
    request: &AppendRunEventRequest,
) -> Result<EventProjection, ServiceError> {
    let current_node = || Some(request.node_id.trim().to_owned());

    match request.event_type {
        RunEventType::RunCreated => Err(ServiceError::InvalidRequest(
            "run_created is generated by the Rust trust core".to_owned(),
        )),
        RunEventType::NodeStarted => {
            ensure_status(run.status, &[RunStatus::Pending, RunStatus::Running])?;
            Ok(EventProjection {
                status: (run.status == RunStatus::Pending).then_some(RunStatus::Running),
                current_node: current_node(),
            })
        }
        RunEventType::NodeFinished => {
            ensure_status(run.status, &[RunStatus::Running])?;
            Ok(EventProjection {
                status: None,
                current_node: current_node(),
            })
        }
        RunEventType::ApprovalRequired => {
            ensure_status(run.status, &[RunStatus::Running])?;
            Ok(EventProjection {
                status: Some(RunStatus::WaitingApproval),
                current_node: current_node(),
            })
        }
        RunEventType::ApprovalResolved => {
            ensure_status(run.status, &[RunStatus::WaitingApproval])?;
            Ok(EventProjection {
                status: Some(RunStatus::Running),
                current_node: current_node(),
            })
        }
        RunEventType::RunStatusChanged => {
            let status = requested_terminal_status(&request.payload)?;
            ensure_terminal_transition(run.status, status)?;
            Ok(EventProjection {
                status: Some(status),
                current_node: current_node(),
            })
        }
        _ => Ok(EventProjection {
            status: None,
            current_node: None,
        }),
    }
}

fn requested_terminal_status(payload: &Map<String, Value>) -> Result<RunStatus, ServiceError> {
    let status = payload
        .get("status")
        .and_then(Value::as_str)
        .and_then(RunStatus::parse)
        .ok_or_else(|| {
            ServiceError::InvalidRequest(
                "run_status_changed payload.status must be success or failed".to_owned(),
            )
        })?;

    match status {
        RunStatus::Success | RunStatus::Failed => Ok(status),
        _ => Err(ServiceError::InvalidRequest(
            "run_status_changed payload.status must be success or failed".to_owned(),
        )),
    }
}

fn ensure_terminal_transition(from: RunStatus, to: RunStatus) -> Result<(), ServiceError> {
    let allowed = matches!(
        (from, to),
        (RunStatus::Pending, RunStatus::Failed)
            | (RunStatus::Running, RunStatus::Success | RunStatus::Failed)
            | (RunStatus::WaitingApproval, RunStatus::Failed)
    );

    if allowed {
        Ok(())
    } else {
        Err(ServiceError::InvalidRequest(format!(
            "run status cannot transition from {} to {}",
            from.as_str(),
            to.as_str()
        )))
    }
}

fn ensure_status(current: RunStatus, allowed: &[RunStatus]) -> Result<(), ServiceError> {
    if allowed.contains(&current) {
        Ok(())
    } else {
        Err(ServiceError::InvalidRequest(format!(
            "event is not allowed while run status is {}",
            current.as_str()
        )))
    }
}

fn parse_run_id(run_id: &str) -> Result<Uuid, ServiceError> {
    Uuid::parse_str(run_id).map_err(|_| ServiceError::InvalidRunId)
}

fn validate_create_run(request: &CreateRunRequest) -> Result<(), ServiceError> {
    validate_required("goal", &request.goal, 4_000)?;
    validate_required("tool.name", &request.tool.name, 200)?;
    validate_required("tool.tool_type", &request.tool.tool_type, 100)?;

    if request.tool.urls.len() > 20 {
        return Err(ServiceError::InvalidRequest(
            "tool.urls must contain at most 20 entries".to_owned(),
        ));
    }

    for url in &request.tool.urls {
        validate_required("tool.urls[]", url, 2_048)?;
    }

    Ok(())
}

fn validate_append_event(request: &AppendRunEventRequest) -> Result<(), ServiceError> {
    validate_required("node_id", &request.node_id, 200)
}

fn validate_required(field: &str, value: &str, max_length: usize) -> Result<(), ServiceError> {
    let value = value.trim();
    if value.is_empty() {
        return Err(ServiceError::InvalidRequest(format!(
            "{field} must not be empty"
        )));
    }
    if value.chars().count() > max_length {
        return Err(ServiceError::InvalidRequest(format!(
            "{field} must contain at most {max_length} characters"
        )));
    }
    Ok(())
}
